language: python
python:
  - 2.7
  - 3.4.3
env:
  - DJANGO=django==1.5.4
  - DJANGO=django==1.6
  - DJANGO=django==1.7
  - DJANGO=django==1.8
  - DJANGO=django==1.9
  - DJANGO=django==1.10
  - DJANGO=django==1.11
install:
  - pip install $DJANGO
  - python setup.py -q install
script: cd access_tokens_test && python manage.py test access_tokens
notifications:
  email: false
